### ISSUE TITLE
Typing "0,1" Causes White Screen on purseboxnft

### ISSUE THREAD

**Issue by ChristianGunawanX** [FunctionX-SG/PurseToken-Interface#49]
Steps to Reproduce:
1. Open https://pursetoken.com/purseboxnft.
2. Type "0,1" into the input field.
3. Observe that the entire screen turns white.

Actual Result: 
The screen turns completely white after entering "0,1", preventing further interaction with the page.

Expected Result: 
The input field handle values "0,1" without crashing.

Attachment
https://drive.google.com/file/d/1GdzcnFTKq3M0xXkgttq2Ge4cvmkNtiVY/view?usp=drive_link

**Comment by fullfatwasabi** [comment]
PR: https://github.com/FunctionX-SG/PurseToken-Interface/pull/52

**Comment by ChristianGunawanX** [comment]
Test Failed
24 Oct 2024
on https://pursetoken.com/purseboxnft
cc @fullfatwasabi 

https://github.com/user-attachments/assets/b024c40f-dff5-4242-9fd2-4284d3dd87dc

**Comment by fullfatwasabi** [comment]
I couldn't recreate this bug with `,` but did so with `.` . Maybe fixed with [this PR](https://github.com/FunctionX-SG/PurseToken-Interface/pull/74) (merged, pending deployment). 

Will update again here when I notice it is completed.

**Comment by fullfatwasabi** [comment]
Hi @ChristianGunawanX, I have just checked and the previous issue I had with the `.` has been fixed.
Could you kindly check if your issue with the `,` has been too?

Thank you!

**Comment by ChristianGunawanX** [comment]
Yes, it solved, thanks @fullfatwasabi 
https://drive.google.com/file/d/1NVlYFBh6p0xHn3X5RdDcoY6-6SOOxgSr/view?usp=drive_link

**Comment by ChristianGunawanX** [comment]
Test Passed
24 OCt 2024
https://pursetoken.com/purseboxnft

https://drive.google.com/file/d/1NVlYFBh6p0xHn3X5RdDcoY6-6SOOxgSr/view?usp=drive_link
