### ISSUE TITLE
Large Gaps Between Cards in Token Pool on Mobile Web

### ISSUE THREAD

**Issue by fullfatwasabi** [FunctionX-SG/PurseToken-Interface#50]
Steps to Reproduce:
1.  Open Farm Page on  'https://pursetoken.com/lpfarm/menu/'  on a mobile web browser.
2. Observe the spacing between cards in the token pool.
3. Notice that the padding is too large, creating excessive gaps between the cards.

Actual Result: 
The cards are spaced far apart due to excessive padding, creating large gaps between them.

Expected Result: 
The padding between cards should be reduced with minimal gaps between cards.

Attachement
https://drive.google.com/file/d/1lyaFD244Rk9i7e6EhffG36tYdr-irhgr/view?usp=drive_link

**Comment by fullfatwasabi** [comment]
PR: https://github.com/FunctionX-SG/PurseToken-Interface/pull/51

**Comment by ChristianGunawanX** [comment]
Test Passed:
24/9/2024
![Image](https://github.com/user-attachments/assets/efcdd4ff-107a-490d-af9f-1f68a5e110bb)
