### ISSUE TITLE
Clicking "Claim" Causes the "Stake" Button to Load Incorrectly

### ISSUE THREAD

**Issue by fullfatwasabi** [FunctionX-SG/PurseToken-Interface#53]
Steps to Reproduce:
1. Open Stake Page on 'https://pursetoken.com/stake' using account can claim reward.
2. Click on the "Claim Reward" button.
3. Observe that the "Stake" button enters a loading state.

Actual Result: 
The "Stake" button enters a loading state when "Claim Reward" is clicked, creating confusion and unnecessary loading.

Expected Result: 
Clicking the "Claim Reward" button unaffected to The "Stake" button.

Attachment:
https://drive.google.com/file/d/1pvMnpcWUgvgZxFr8iuIIPDZ1SAofJMHr/view?usp=drive_link

**Comment by fullfatwasabi** [comment]
PR: https://github.com/FunctionX-SG/PurseToken-Interface/pull/54

**Comment by ChristianGunawanX** [comment]
Test Passed
24/9/2024
https://github.com/user-attachments/assets/64a99e34-139c-4caf-ba7c-6eeedf0e75eb
