### ISSUE TITLE
Card Box Size Too Large in Mobile UI

### ISSUE THREAD

**Issue by fullfatwasabi** [FunctionX-SG/PurseToken-Interface#55]
Steps to Reproduce:
1. Open Purse Box page on 'https://pursetoken.com/purseboxnft' on a mobile UI.
2. Observe that the card boxes are too large, creating an unbalanced layout.

Actual Result: 
The card boxes remain large, causing unnecessary gaps and inefficient use of screen space.

Expected Result: 
The card boxes should scale down to a more appropriate size in mobile view, ensuring a compact, user-friendly layout.

Attachment
![Image](https://github.com/user-attachments/assets/843e5f56-6f52-4c24-8c7f-af682c4a5b0b)

**Comment by fullfatwasabi** [comment]
PR: https://github.com/FunctionX-SG/PurseToken-Interface/pull/56

**Comment by ChristianGunawanX** [comment]
Test Failed
24/9/2024

![Image](https://github.com/user-attachments/assets/ff5cc9ca-f7c9-472b-a2d1-d8181c284cde)

**Comment by fullfatwasabi** [comment]
@ChristianGunawanX,

Just checking if the issue is the footer or the NFT image sizes?

If it is the footer, I noticed it in other pages too so I had created a new issue previously but apparently accidentally closed it
https://github.com/FunctionX-SG/PurseToken-Interface/issues/57

**Comment by ChristianGunawanX** [comment]
The main content on the Pursebox page extends too wide, which makes the footer look disproportionately small or squeezed in comparison

@fullfatwasabi

**Comment by fullfatwasabi** [comment]
Ah ok thanks for the clarification @ChristianGunawanX, is it ok if I close this issue since it is a subset of issue https://github.com/FunctionX-SG/PurseToken-Interface/issues/57?

**Comment by fullfatwasabi** [comment]
Hi @ChristianGunawanX, sorry I missed this. Fixed in PR: https://github.com/FunctionX-SG/PurseToken-Interface/pull/71. (Merged but not yet deployed)

**Comment by ChristianGunawanX** [comment]
Okay, noted, just ping me if done deployed, thanks

**Comment by ChristianGunawanX** [comment]
Test Passed
24 Oct 2024
on https://pursetoken.com/purseboxnft
<img width="324" alt="Screenshot 2024-10-24 at 09 49 00" src="https://github.com/user-attachments/assets/66533fd7-b58d-4bd6-b139-e1d1b6fd1d95">
