### ISSUE TITLE
Add TVL chart for farm and staking

### ISSUE THREAD

**Issue by CheeKeat10** [FunctionX-SG/PurseToken-Interface#68]

**Comment by fullfatwasabi** [comment]
subgraph endpoint:
https://api.goldsky.com/api/public/project_clz6ti9bm1qjm01086dflgsh3/subgraphs/pursetoken/0.0.2/gn

**Comment by ChristianGunawanX** [comment]
Test Passed
28 Oct 2024
https://pursetoken.com/#/stake

https://github.com/user-attachments/assets/303251e7-b8af-46f3-86ea-48cd9f6a3971
