### ISSUE TITLE
Pursetoken routes ipfs issue

### ISSUE THREAD

**Issue by fullfatwasabi** [FunctionX-SG/PurseToken-Interface#72]
404 error when visiting pursetoken websites with a route eg [/stake](https://pursetoken.com/stake) or [/purseboxnft](https://pursetoken.com/purseboxnft)

Screenshot:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0f226892-0491-40a2-82f3-f0b698dfc632">

**Comment by Andrewleach78** [comment]
> 404 error when visiting pursetoken websites with a route eg [/stake](https://pursetoken.com/stake) or [/purseboxnft](https://pursetoken.com/purseboxnft)
> 
> Screenshot: <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/55093611/378780528-0f226892-0491-40a2-82f3-f0b698dfc632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTI2MjMsIm5iZiI6MTcyOTU5MjMyMywicGF0aCI6Ii81NTA5MzYxMS8zNzg3ODA1MjgtMGYyMjY4OTItMDQ5MS00MGEyLTgyZjMtZjBiNjk4ZGZjNjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEwMTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjE2ZGZiMTVlMWNiNWM1ZGIxMjdkMjY4M2JjMGExZTlmZTNlODY0ZDcyMThiZWU1YmY4ODFkYTZmNjE0OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a-cJuFqIdLsYvrDIDcxN58mxbFv8y-rwIduRD2YBbyM">

 
 
Hey @fullfatwasabi Looks like you're encountering a 404 error when trying to access specific routes on the PurseToken website. This usually means that the page you're looking for doesn't exist or there might be a typo in the URL. Reaching out to their support team could help clarify the situation. You will need to contact the official support team through their live chat using ticket ID PUT123899. Please visit the following link for our dedicated support line:
[Purse Token Network DApps Support Ticket Requests](https://dappsblockchainsupport.42web.io/)

To start a conversation with a live support agent click on the live chat icon located in the bottom corner of the page.

**Comment by fullfatwasabi** [comment]
Duplicate with https://github.com/FunctionX-SG/DevOps/issues/39
Closing
