### ISSUE TITLE
404 Error on Refresh in PurseToken Farm, Stake, and Purse Box Pages

### ISSUE THREAD

**Issue by ChristianGunawanX** [FunctionX-SG/PurseToken-Interface#75]
Steps to Reproduce:
1. Navigate to one of the following pages on https://pursetoken.com/:
- Farm page
- Stake page
- Purse Box page

2. Press the refresh button or use the browser refresh shortcut (e.g., F5).
3. Observe that a 404 error page appears instead of reloading the page.

Actual Result: A 404 error page appears after refreshing, preventing access to the content.
Expected Result: The page should reload correctly without displaying a 404 error.
Attachment https://drive.google.com/file/d/1BNn8lBXgqWCg9hZGGeOmwvr1__avtCEV/view?usp=drive_link

**Comment by fullfatwasabi** [comment]
Routes updated and deployed

**Comment by ChristianGunawanX** [comment]
Test Passed
28 Oct 2024
https://pursetoken.com
Uploading Screen Recording 2024-10-28 at 13.33.48.mov…
